#!/usr/bin/env bash
# Build the six stagent release binaries, write SHA256SUMS and, inside the
# SSH Term app tree, regenerate the app's pinned release constants
# (lib/services/agent_bridge/stagent_release.dart).
#
#   scripts/release.sh             build into dist/ (and regenerate the Dart file)
#   scripts/release.sh --publish   additionally create the GitHub release
#                                  v<version> in obutora/stagent (needs gh)
#
# Builds are reproducible (-trimpath, no VCS stamp, empty build id), so the
# same source and Go toolchain always give the same sha256 sums: the app pins
# them, and the release must be published from the exact tree that generated
# the Dart file. Run it from a checkout of the public source repository to
# check a release: dist/SHA256SUMS must match the release's. Set GO to use a
# specific toolchain.
set -euo pipefail

publish=0
for arg in "$@"; do
  case "$arg" in
    --publish) publish=1 ;;
    -h|--help) sed -n '2,15p' "$0"; exit 0 ;;
    *) echo "release.sh: unknown argument: $arg" >&2; exit 2 ;;
  esac
done

here="$(cd "$(dirname "$0")/.." && pwd)"     # stagent module root
app="$(cd "$here/.." && pwd)"                 # Flutter app root
dist="$here/dist"
dart_out="$app/lib/services/agent_bridge/stagent_release.dart"
repo="obutora/stagent"
go="${GO:-go}"

version="$(sed -n 's/^const Version = "\(.*\)"$/\1/p' "$here/internal/version/version.go")"
if [ -z "$version" ]; then
  echo "release.sh: cannot read Version from internal/version/version.go" >&2
  exit 1
fi
base_url="https://github.com/$repo/releases/download/v$version"
targets="linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 windows/amd64 windows/arm64"

if command -v sha256sum >/dev/null 2>&1; then
  sha() { sha256sum "$1" | cut -d' ' -f1; }
else
  sha() { shasum -a 256 "$1" | cut -d' ' -f1; }
fi

asset() { # asset <os>-<arch> → release file name
  case "$1" in windows-*) echo "stagent-$1.exe" ;; *) echo "stagent-$1" ;; esac
}

rm -rf "$dist"
mkdir -p "$dist"
echo "stagent $version ($("$go" version))"
for t in $targets; do
  os="${t%/*}" arch="${t#*/}"
  name="$(asset "$os-$arch")"
  echo "  build $name"
  (cd "$here" && CGO_ENABLED=0 GOOS="$os" GOARCH="$arch" "$go" build \
    -trimpath -buildvcs=false -ldflags '-s -w -buildid=' \
    -o "$dist/$name" ./cmd/stagent)
done

: > "$dist/SHA256SUMS"
for t in $targets; do
  name="$(asset "${t%/*}-${t#*/}")"
  printf '%s  %s\n' "$(sha "$dist/$name")" "$name" >> "$dist/SHA256SUMS"
done

# The public source repository has no app next to it; there SHA256SUMS is
# the whole output.
if [ -f "$app/pubspec.yaml" ]; then
tmp="$(mktemp "${dart_out}.XXXXXX")"
{
  cat <<'EOF'
// GENERATED by stagent/scripts/release.sh — do not edit.
// ignore_for_file: lines_longer_than_80_chars

/// Release of the stagent server binary this app installs.
EOF
  printf "const String stagentVersion = '%s';\n\n" "$version"
  cat <<'EOF'
/// Base URL of the release assets (`<base>/<asset name>`).
const String stagentReleaseBaseUrl =
EOF
  printf "    '%s';\n\n" "$base_url"
  cat <<'EOF'
/// Expected sha256 (lowercase hex) of each release asset, keyed `<os>-<arch>`.
const Map<String, String> stagentSha256 = {
EOF
  for t in $targets; do
    key="${t%/*}-${t#*/}"
    sum="$(awk -v n="$(asset "$key")" '$2 == n { print $1 }' "$dist/SHA256SUMS")"
    printf "  '%s': '%s',\n" "$key" "$sum"
  done
  cat <<'EOF'
};

/// File name of the release asset for [assetKey] (`<os>-<arch>`).
String stagentAssetName(String assetKey) =>
    assetKey.startsWith('windows-') ? 'stagent-$assetKey.exe' : 'stagent-$assetKey';

/// Download URL of the release asset for [assetKey].
String stagentAssetUrl(String assetKey) =>
    '$stagentReleaseBaseUrl/${stagentAssetName(assetKey)}';
EOF
} > "$tmp"
mv "$tmp" "$dart_out"
echo "wrote $dist/SHA256SUMS and $dart_out"
else
echo "wrote $dist/SHA256SUMS"
fi
cat "$dist/SHA256SUMS"

if [ "$publish" = 1 ]; then
  command -v gh >/dev/null 2>&1 || { echo "release.sh: gh is required for --publish" >&2; exit 1; }
  gh release create "v$version" "$dist"/* \
    --repo "$repo" \
    --title "stagent v$version" \
    --notes "stagent $version — server binary for SSH Term Agent Mode. Verify downloads against SHA256SUMS."
  echo "published $base_url"
fi
